### ISSUE TITLE
Serialize a single tag to YAML

### ISSUE THREAD

**Issue by Mimickal** [Mimickal/Librarian#1]
Pick a simple tag type and export it to YAML

There will be a lot of project setup stuff in this branch too.

**Comment by ShellyHerself** [comment]
I suggest actor, nice and simple

**Comment by Mimickal** [comment]
Well this took a lifetime to pick back up.
But here's basic Actor serialization! https://github.com/Sigmmma/Librarian/commit/4b3fd43c3f2f3eaaa22ae614921573aab27f1b64
